### ISSUE TITLE
Underline problem with Scala

### ISSUE THREAD

**Issue by ankitbko** [alexnho/vscode-a-touch-of-lilac-theme#14]
All the type names are underlined in Scala. This problem only happens with the no italic version 1.22. I tested Java, .NET and python code but they do not have this problem of being underlined.

![image](https://user-images.githubusercontent.com/3169316/78547541-e5521280-781c-11ea-8d07-7bc21f0952db.png)

This is how it looks with italic version - 
![image](https://user-images.githubusercontent.com/3169316/78547689-1cc0bf00-781d-11ea-9f94-572fe488cf12.png)

**Comment by alexnho** [comment]
Hi @ankitbko ,

Thanks for pointing out the issue, it seems it came from the fact that there were 2 `Class name` declarations and one of them was inheriting from the other the `font styles (underline)`.
With the latest publish (ver. 1.2.3) I think your issue for Scala should be fixed. Give it a try.

Regards

**Comment by ankitbko** [comment]
Brilliant! Works perfectly. Thanks for quick fix.
