### ISSUE TITLE
editor.selectionHighlightBackground must not be opaque so as not to hide underlying decorations.

### ISSUE THREAD

**Issue by JacksonKearl** [alexnho/vscode-a-touch-of-lilac-theme#2]
Currently it is impossible to differentiate between a word hilighted because it matches the current token and one hilighted because it matches the current token and is being selected. I personally chainged it to be:
```json
"editor.selectionHighlightBackground": "#ff00ff33"
```

For the result:
![image](https://user-images.githubusercontent.com/8586769/52816374-f60e5a80-3055-11e9-8da7-399fa7dea578.png)
Where the first cons is selected, the second is selected and hilighted, and the third is just hilighted.

**Comment by alexnho** [comment]
Hi @JacksonKearl , I've updated the theme with the color you mention since it looks good to me.
Thanks for your help!
