### ISSUE TITLE
No Italic version

### ISSUE THREAD

**Issue by FatTonyy** [alexnho/vscode-a-touch-of-lilac-theme#8]
awesome theme but can you make a no italic version?

**Comment by alexnho** [comment]
Thanks for the feedback, I can't promise that I'll do a `no-italic` version, I can only say that maybe I'll look into it at some point in time.
Regards

**Comment by ankitbko** [comment]
+1 for this request. Or maybe have a setting to toggle it.

**Comment by alexnho** [comment]
Hi @FatTonyy , @ankitbko ,

Since it was requested by you guys, I've also added a No-Italics for this theme. :)
You can give it a try with ver. 1.2.1 

Regards
